export const defaultPolicyContent = {
  privacyPolicyPageTitle: {
    en: 'Privacy Policy',
    sv: 'Integritetspolicy',
    fi: 'Tietosuojakaytanto',
    da: 'Privatlivspolitik',
  },
  privacyPolicyPageContent: {
    en: '# Privacy Policy\n\nWe collect only the information needed to process orders, support your account, and improve the store.\n\n## What we collect\n\n- Account details such as your name and email address\n- Order, shipping, and payment-related information\n- Support requests, returns, and review submissions\n- Optional analytics and marketing preferences when you consent\n\n## How we use your data\n\n- To process purchases and deliver orders\n- To provide customer support and manage refunds or returns\n- To prevent fraud, abuse, and security incidents\n- To improve the storefront experience and communications\n\n## Analytics and consent\n\nWe only enable optional analytics tools such as PostHog and Microsoft Clarity after you give consent. You can change your preferences at any time from the footer cookie settings.\n\n## Marketing emails\n\nIf you opt in, we may send product news, launches, and editorial updates. Every email includes an unsubscribe option.\n\n## Your rights\n\nDepending on your location, you may request access, correction, deletion, or restriction of your personal data.\n\n## Contact\n\nIf you have questions about privacy, please contact support through the store.',
    sv: '# Integritetspolicy\n\nVi samlar endast in den information som behovs for att behandla bestallningar, hantera ditt konto och forbattrar butiken.\n\n## Vad vi samlar in\n\n- Kontouppgifter som namn och e-postadress\n- Order-, leverans- och betalningsrelaterad information\n- Supportarenden, returer och recensioner\n- Valfria analys- och marknadsforingsinstallningar nar du samtycker\n\n## Hur vi anvander dina uppgifter\n\n- For att behandla kop och leverera bestallningar\n- For att ge kundsupport och hantera returer eller aterbetalningar\n- For att forebygga bedrägeri, missbruk och sakerhetsincidenter\n- For att forbattrar butiksupplevelsen och kommunikationen\n\n## Kontakt\n\nOm du har fragor om integritet, kontakta supporten via butiken.',
    fi: '# Tietosuojakaytanto\n\nKeraamme vain tiedot, joita tarvitaan tilausten kasittelyyn, tilisi hallintaan ja kaupan parantamiseen.\n\n## Mita keraamme\n\n- Tilitiedot, kuten nimi ja sahkopostiosoite\n- Tilaus-, toimitus- ja maksutiedot\n- Tukipyynnot, palautukset ja arvostelut\n- Valinnaiset analytiikka- ja markkinointiasetukset suostumuksesi perusteella\n\n## Miten kaytamme tietojasi\n\n- Ostosten kasittelyyn ja tilausten toimittamiseen\n- Asiakastuen seka palautusten ja hyvitysten hoitamiseen\n- Petosten, vaarinkaytosten ja turvallisuusongelmien ehkaisyyn\n- Kaupan kayttokokemuksen ja viestinnan parantamiseen\n\n## Yhteys\n\nJos sinulla on tietosuojaan liittyvia kysymyksia, ota yhteytta tukeen kaupan kautta.',
    da: '# Privatlivspolitik\n\nVi indsamler kun de oplysninger, der er nodvendige for at behandle ordrer, administrere din konto og forbedre butikken.\n\n## Hvad vi indsamler\n\n- Kontooplysninger som navn og e-mailadresse\n- Ordre-, leverings- og betalingsrelaterede oplysninger\n- Supporthenvendelser, returneringer og anmeldelser\n- Valgfrie analyse- og marketingpraeferencer nar du giver samtykke\n\n## Hvordan vi bruger dine data\n\n- Til at behandle kob og levere ordrer\n- Til at yde kundesupport og handtere returneringer eller refunderinger\n- Til at forhindre svindel, misbrug og sikkerhedshaendelser\n- Til at forbedre butiksoplevelsen og kommunikationen\n\n## Kontakt\n\nHvis du har sporgsmal om privatliv, kontakt support gennem butikken.',
  },
  cookiePolicyPageTitle: {
    en: 'Cookie Policy',
    sv: 'Cookiepolicy',
    fi: 'Evastekaytanto',
    da: 'Cookiepolitik',
  },
  cookiePolicyPageContent: {
    en: '# Cookie Policy\n\nWe use cookies and similar technologies to keep the store secure and working properly.\n\n## Essential cookies\n\nEssential cookies support login sessions, carts, checkout, fraud prevention, and language or preference memory.\n\n## Optional analytics cookies\n\nIf you allow analytics, we may use tools such as PostHog and Microsoft Clarity to understand how visitors use the store and where the experience can be improved.\n\n## Managing your preferences\n\nYou can accept or reject optional cookies from the consent banner and reopen those settings at any time from the footer.\n\n## Marketing preferences\n\nMarketing email consent is stored separately from analytics preferences. You can unsubscribe from marketing emails at any time.\n\n## Contact\n\nIf you need more details, review our privacy policy or contact support.',
    sv: '# Cookiepolicy\n\nVi anvander cookies och liknande teknik for att halla butiken saker och fungerande.\n\n## Nodvandiga cookies\n\nNodvandiga cookies stodjer inloggning, kundvagn, kassa, bedraegeriskydd och sprak- eller preferensminne.\n\n## Valfria analyscookies\n\nOm du tillater analys kan vi anvanda verktyg som PostHog och Microsoft Clarity for att forsta hur besokare anvander butiken och var upplevelsen kan forbattras.\n\n## Hantera dina installningar\n\nDu kan acceptera eller neka valfria cookies fran samtyckesbannern och oppna installningarna igen nar som helst fran sidfoten.',
    fi: '# Evastekaytanto\n\nKaytamme evasteita ja vastaavia tekniikoita pitaaaksemme kaupan turvallisena ja toimivana.\n\n## Valttamattomat evasteet\n\nValttamattomat evasteet tukevat kirjautumista, ostoskoria, kassaa, petostentorjuntaa seka kieli- ja valintamuistia.\n\n## Valinnaiset analytiikkaevasteet\n\nJos sallit analytiikan, voimme kayttaa tyokaluja kuten PostHogia ja Microsoft Claritya ymmartaaksemme kayttoa ja parantaaksemme kokemusta.\n\n## Asetusten hallinta\n\nVoit hyvaksya tai hylata valinnaiset evasteet suostumusbannerista ja avata asetukset uudelleen milloin tahansa alatunnisteesta.',
    da: '# Cookiepolitik\n\nVi bruger cookies og lignende teknologier for at holde butikken sikker og velfungerende.\n\n## Nodvendige cookies\n\nNodvendige cookies understotter login, kurv, checkout, svindelforebyggelse samt hukommelse for sprog og praeferencer.\n\n## Valgfrie analysecookies\n\nHvis du tillader analyse, kan vi bruge vaerktojer som PostHog og Microsoft Clarity til at forsta, hvordan besogende bruger butikken, og hvor oplevelsen kan forbedres.\n\n## Handtering af dine praefrencer\n\nDu kan acceptere eller afvise valgfrie cookies fra samtykkebanneret og abne indstillingerne igen nar som helst fra footeren.',
  },
  termsOfServicePageTitle: {
    en: 'Terms of Service',
    sv: 'Anvandarvillkor',
    fi: 'Kayttoehdot',
    da: 'Vilkår',
  },
  termsOfServicePageContent: {
    en: '# Terms of Service\n\nBy creating an account or placing an order, you agree to use the store lawfully and to provide accurate information.\n\n## Accounts\n\n- Keep your login credentials secure.\n- You are responsible for activity under your account.\n- We may suspend accounts involved in abuse, fraud, or unlawful use.\n\n## Orders and payments\n\n- Prices, taxes, and shipping are confirmed during checkout.\n- Orders may be delayed, cancelled, or refused in cases of fraud, stock issues, or payment problems.\n\n## Returns and support\n\nOur shipping, returns, and privacy pages explain the latest support and refund process.\n\n## Intellectual property\n\nStore content, product imagery, branding, and editorial material may not be copied or reused without permission.\n\n## Contact\n\nIf you have questions about these terms, please contact support through the store.',
    sv: '# Anvandarvillkor\n\nGenom att skapa ett konto eller lagga en bestallning godkanner du att anvanda butiken lagligt och att lamna korrekta uppgifter.',
    fi: '# Kayttoehdot\n\nLuomalla tilin tai tekemalla tilauksen hyvaksyta kaupan laillisen kayton ja oikeiden tietojen antamisen.',
    da: '# Vilkar\n\nVed at oprette en konto eller afgive en ordre accepterer du at bruge butikken lovligt og at give korrekte oplysninger.',
  },
} as const;
